language: python
python:
  - "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE = Native_Service.test_settings


install:
  - echo "PIPENV BUILD ENV"
  - pip install -r requirements.txt

script:
  - echo "TEST"
  - black ./
  - python ./CI_runner.py
