language: python
python:
  - "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE = Native_Service.test_settings


install:
  - echo "PIPENV BUILD ENV"
  - pip install pipenv
  - pip install black
  - pip install django
  - pip install widget_tweaks
  - pip install crispy_forms
  - pip install favicon

script:
  - echo "BLACK"
  - black ./
  - ls
  - pwd
  - python ./CI_runner.py
  - python -m pytest Native_Service/


