language: python

env:
  global:
    - DJANGO_SETTINGS_MODULE = native_service_API.settings.py

install:
  - echo "PIPENV BUILD ENV"
  - pip install pipenv
  - pipenv sync --clear
  - pipenv run black
script:
  - echo "BLACK"
  - black --check *.py
  - pytest
