language: python
python:
  - "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE = Native_Service.test_settings


install:
  - echo "PIPENV BUILD ENV"
  - pip install requirements.txt
  - pip install black
  - pip install django
  - pip install django-widget-tweaks
  - pip install --upgrade django-crispy-forms
  - pip install favicon

script:
  - echo "BLACK"
  - black ./
  - ls
  - pwd
  - python ./CI_runner.py


