language: python
python:
  - "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE = native_service_API.settings.py


install:
  - echo "PIPENV BUILD ENV"
  - pip install pipenv
  - pip install black
  - pip install django
  - whereis black
  - black -h

script:
  - echo "BLACK"
  - black ./
  - ls
  - pwd
  - python -m pytest Native_Service/
