language: python
python:
  - "3.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE = native_service_API.settings.py


install:
  - echo "PIPENV BUILD ENV"
  - 'pip install pipenv'
  - 'pipenv install'
  - whereis black
  - pipenv whereis black
  - pipenv run black
script:
  - echo "BLACK"
  - black --check *.py
  - pytest
