# Generated by Django 2.2.2 on 2019-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Native_Service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalPricing',
        ),
        migrations.AddField(
            model_name='nativepost',
            name='comments',
            field=models.CharField(max_length=500, null=True, verbose_name='Komentarz do zlecenia'),
        ),
        migrations.AddField(
            model_name='nativepost',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Cena'),
        ),
        migrations.AddField(
            model_name='nativepost',
            name='time_to_get_ready',
            field=models.DateField(null=True, verbose_name='Szacowany czas realizacji zlecenia'),
        ),
        migrations.AlterField(
            model_name='nativepost',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
