# Generated by Django 2.2.2 on 2019-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Native_Service", "0003_comments_field_changed_on_textfield")]

    operations = [
        migrations.AlterField(
            model_name="nativepost",
            name="secret_key",
            field=models.CharField(max_length=45),
        )
    ]
