# Generated by Django 2.2.2 on 2019-06-24 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Native_Service', '0010_category_and_priority_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativepost',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
